#pragma config(Sensor, S1,     rightS,         sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     leftS,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     reflect,        sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// Use this program to calibrate values for robertTools.h library

float speed = 4.5; //10 old //7.5 OG
float ltSpeed = 3;
bool hold = false; //keeps exiting function :(
float turnDist;

task display() //Display for Error Log
{
	repeat(forever){
		displayBigTextLine(2, "LCS: %d", getColorName(leftS));
		displayBigTextLine(4, "RCS: %d", getColorName(rightS));
		displayBigTextLine(6, "SS: %d", SensorValue[S4]);
		displayBigTextLine(8, "LeftM: %d", getMotorEncoder(leftMotor));
		displayBigTextLine(10, "RightM: %d", getMotorEncoder(rightMotor));
		displayBigTextLine(12, "turnDist: %d", turnDist);
		sleep(20); //refreshrate in ms
	}
}
void rsMotors(){
	resetMotorEncoder(motorB);
	resetMotorEncoder(motorC);
}
void STP(){//Stop
	motor[motorB] = 0;
	motor[motorC] = 0;
}

void leftMotorMove(){
	motor[leftMotor]=(-ltSpeed);
	motor[rightMotor]=(ltSpeed);
}
void rightMotorMove(){
	motor[leftMotor]=(ltSpeed);
	motor[rightMotor]=(-ltSpeed);
}


void moveOnLine(){
	hold = true;
	while(hold == true){
		leftMotorMove();
		if(getColorName(leftS) == colorWhite){
			STP();
			turnDist = getMotorEncoder(motorB);
			playSound(soundDownwardTones);
			sleep(5000);
			stopAllTasks();
		}
	}
}
task main(){
	playSound(soundFastUpwardTones);//Start of experiment
	repeat(forever){
		startTask(display);
		sleep(300);
		rsMotors();
		if(getColorName(leftS) == colorWhite){
			leftMotorMove();
		}
		if(getColorName(leftS) == colorBlack){
			STP();
			sleep(200);
			hold = true;
			moveOnLine();//Alligns itself onto the line
		}
	}
}
