#pragma config(Sensor, S1,     leftS,          sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     rightS,         sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool equals(int *arr1, int *arr2, int size){
	int equal = 0;
	for(int i = 0; i<size; i++){
		if(arr1[i]==arr2[i]){
			equal++;
		}
	}
	if(equal==size){
		return true;
	}
	else{
		return false;
	}
}
//compares arrays of any size

bool equals(int *arr1, int *arr2) //compares arrays of size three
{
	if((arr1[0]==arr2[0])&&(arr1[1]==arr2[1])&&(arr1[2]==arr2[2])){
		return true;
	}
	else{
		return false;
	}
}

//bool equals(string str1, string str2){
//	StringFind(str1, str2>=0)
//} //review for acuracy

//void calculate(int *arr1, int *arr2, int size){
//		for
//}


