#pragma config(Sensor, S1,     leftS,          sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     rightS,         sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    int lr,lg,lb; // create the variables

    // Repeatedly do what is in the brackets
    while (true) {
        // Like scanf, input colour intensities into variables
        getColorRawRGB(leftS, lr, lg, lb);

        // Print it on the 2nd line of the screen
        displayCenteredTextLine(2, "%d %d %d", lr, lg, lb);
    }
}

//https://fshsrobotics.gitlab.io/c-course/sensors-and-motors/
// intersting site https://robocatz.com/competition-robots.htm
