#pragma config(Sensor, S1,     rightS,         sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     leftS,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     reflect,        sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "\lib\teamTools.h"
float robotWidth = 13.6;
float robotLength = 17;
float maxObstacleSize = 14;
bool hasObstacle = false;
float obstacleDistance = 3; //the distance when it will see the obstacle in cm (confirm this)
float turnDistance= robotWidth/2;  // 1 is margin error



void checkObstacle(int x)
{
	if (SensorValue[S4] <= x)
	{
		hasObstacle = true;
	}
	else
	{
		hasObstacle = false;
	}
}

task display() //Display for Error Log
{
	repeat(forever){
	displayBigTextLine(6, "SS: %d", SensorValue[S4]);
	displayBigTextLine(8, "LeftM: %d", getMotorEncoder(leftMotor));
	displayBigTextLine(10, "RightM: %d", getMotorEncoder(rightMotor));
	sleep(10); //refreshrate in ms
	}
}


void avoidObstacle()
{
	checkObstacle(obstacleDistance);
	resetMotorEncoder(motorB);
	resetMotorEncoder(motorC);
	encoderBackward(turnDistance-obstacleDistance);

	if (hasObstacle == true)
	{
		STP();
		sleep(1000);
		encoderPointLeft();
		encoderForward(robotWidth);
		encoderPointRight();
		checkObstacle(obstacleDistance);
	  }

		resetMotorEncoder(motorB);
		resetMotorEncoder(motorC);

		encoderForward((obstacleDistance+robotLength)+(2*turnDistance));

		encoderPointRight();
		resetMotorEncoder(motorB);
		resetMotorEncoder(motorC);
			while((getColorName(leftS)==colorWhite)||(getColorName(leftS)==colorWhite)){
			motorForward(5);
			}
			sleep(500);
			encoderPointLeft();
			STP();
			sleep(500);
}

void properties(){
		//setMotorDirection('f');
		//setWheelDiameterCM(7.455);
		setUTURN(330);
		setPoint(150);
		setSpeed(10);
		setLeanSpeed(6);
		setSearchSpeed(6);
		setDist(2.5);
		setTapeThreasholdCM(5);
		setSearchSpeed(6);
		setSearchTime(10000);
}
task main()
{
	properties();
	startTask(display);
	//repeat(forever)
	//{
		while(SensorValue[S4] > obstacleDistance){
			motorForward(5);
		}

		STP();
		avoidObstacle();
	//}
}
